### PR TITLE
Stream parameter name added

### PR DESCRIPTION
**Pull request by itsstilldre**
Change-Id: Iadb7df787c23c39928410edbb44a4ca0acb88f37

### CODE REVIEW

**Comment by itsstilldre** [comment]
Hi in our project, we will need this "name" parameter of the streams. Please review the code.

**Comment by leomaatEric** [comment]
thanks for your contribution, I will review it ASAP

**Comment by Emil-Gustafsson** [comment]
i dont understand this, this is same as ID, just added stream in front of it. Why cant you use the ID as the name? if you want to have a name in some scenario just take the ID and add "stream" infront of it there.

**Comment by itsstilldre** [comment]
I have created a constructor with tha name parameter as well. If you don't want to give name, then the default could be "Stream" + id.

**Comment by itsstilldre** [comment]
The RPC request payload is put together based on this classes fields, right? so if I would like to have teh name in the payload, then I need a field name in this class. It seems like the most simple solution.

**Comment by itsstilldre** [comment]
According to the Python API documentation (which is the fresh documentation as far as I know) The stream naem parameter is used for the following:

name : string
Name of the stream. Required if this stream is dependent on another stream, and another stream needs to refer to this stream by name.

**Comment by itsstilldre** [comment]
https://trex-tgn.cisco.com/trex/doc/cp_stl_docs/api/profile_code.html#stlstream

**Comment by Emil-Gustafsson** [comment]
the python api and rpc api is not the same, here ID is used instead, if i understand correctly the ID will be included in the payload when you have enabled flow stats, not sure if it is included in any case even

**Comment by itsstilldre** [comment]
Ok, I need to check out more information about what we need. Thank you for the feedback.

**Comment by itsstilldre** [comment]
Could you help me maybe if you have a good documentation about the T-Rex server, what RPC methods does it support, and what are the payload parameters, so on? because anything I found on the internet is either deprecated or some kind of python documentation that si not completely applicable for this java sdk. It would be very much appreciated.

**Comment by Emil-Gustafsson** [comment]
Here is the doc for rpc api.
https://github.com/cisco-system-traffic-generator/trex-core/blob/master/doc/trex_rpc_server_spec.asciidoc

**Comment by itsstilldre** [comment]
> Here is the doc for rpc api.
> https://github.com/cisco-system-traffic-generator/trex-core/blob/master/doc/trex_rpc_server_spec.asciidoc

Yes, well in this documentation Get Stream Stats is present, which is a method that does not exist. Also, the description of it is a copy paste error from get port stats. This is a deprecated documentation that I was talking about :)

**Comment by leomaatEric** [comment]
Actually this is the official documents of RPC specification, it may not sync with the trex-software update timely, so some content is out of date somehow.

**Pull request closed without merging**
