### PR TITLE
support astf traffic low-level api 

### PR DESCRIPTION
**Pull request by StanleyWu51**
this pull request could support low-level traffic api to load profile. 
some python script in "\automation\trex_control_plane\interactive\trex\astf" had been rewritten in java way in this PR to support astf traffic

### CODE REVIEW

**Comment by leomaatEric** [comment]
Hi Stanley,
Since it's a huge code base in your commits. can you just paste a code piece to explain how these new APIs are used for loading profile comparing the python low_level APIs.

**Comment by StanleyWu51** [comment]
Hi leo 
take "\astf\http_manual_commands.py" for example , in this python file,
```
    def create_profile(self):
        # client commands
        prog_c = ASTFProgram()
        ........
        .......
        # profile
        profile = ASTFProfile(default_ip_gen=ip_gen, templates=template)
        return profile

    def get_profile(self, **kwargs):
        return self.create_profile()
```
The main purpose is to get ASTFProfile instance. and then using load_profile(ASTFProfile) method and start method to send stateful traffic. in load_profile method. it will get all raw json data from ASTFProfile.

what we have done is provide the same java classes to do that. that means we can code like python way to generate AstfProfile and loadProfile or sendTraffic like python.
so we can code to generate AstfProfile class in java way as follows by contrast:
```
    public AstfProfile createProfile() {
        String http_response = "HTTP/1.1 200 OK\r\nServer: Microsoft-IIS/6.0\r\nContent-Type: text/html\r\nContent-Length: 32000\r\n\r\n<html><pre>**********</pre></html>";
        String http_req = "GET /3384 HTTP/1.1\r\nHost: 22.0.0.3\r\nConnection: Keep-Alive\r\nUser-Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; SV1; .NET CLR 1.1.4322; .NET CLR 2.0.50727)\r\nAccept: */*\r\nAccept-Language: en-us\r\nAccept-Encoding: gzip, deflate, compress\r\n\r\n";

        //client
        AstfProgram progC = new AstfProgram();
        progC.send(http_req);
        progC.recv(http_response.length());

        //server
        AstfProgram progS = new AstfProgram();
        progS.recv(http_req.length());
        progS.send(http_response);

        //ip generator
        AstfIpGenDist ipGenClient = new AstfIpGenDist("16.0.0.0", "16.0.0.255");
        AstfIpGenDist ipGenServer = new AstfIpGenDist("48.0.0.0", "48.0.255.255");
        AstfIpGen ipGen = new AstfIpGen(ipGenClient, ipGenServer, new AstfIpGenGlobal("1.0.0.0"));

        //template
        AstfTcpClientTemplate tempC = new AstfTcpClientTemplate(progC, ipGen, null, 80, 1, null, 0);
        AstfTcpServerTemplate tempS = new AstfTcpServerTemplate(progS,null,null);
        AstfTemplate template = new AstfTemplate(tempC, tempS);

        List<AstfTemplate> templateList=new ArrayList();
        templateList.add(template);

        AstfProfile profile = new AstfProfile(ipGen, null, null, templateList, null);
        return profile;
    }
```
when we get AstfProfile instance, we can invoke AstfProfile#toJson to get the raw json data. that's what we want.

**Comment by hhaim** [comment]
@StanleyWu51 look almost identical to the python profile. nice work. Did you follow the python code?

**Comment by StanleyWu51** [comment]
Hi @hhaim 
Yes, All java classes is based on python code in "\automation\trex_control_plane\interactive\trex\astf".
by using jave code as my previous comment.  the profile raw json data result is 
```
{"buf_list":["R0VUIC8zMzg0IEhUVFAvMS4xDQpIb3N0OiAyMi4wLjAuMw0KQ29ubmVjdGlvbjogS2VlcC1BbGl2ZQ0KVXNlci1BZ2VudDogTW96aWxsYS80LjAgKGNvbXBhdGlibGU7IE1TSUUgNy4wOyBXaW5kb3dzIE5UIDUuMTsgU1YxOyAuTkVUIENMUiAxLjEuNDMyMjsgLk5FVCBDTFIgMi4wLjUwNzI3KQ0KQWNjZXB0OiAqLyoNCkFjY2VwdC1MYW5ndWFnZTogZW4tdXMNCkFjY2VwdC1FbmNvZGluZzogZ3ppcCwgZGVmbGF0ZSwgY29tcHJlc3MNCg0K","SFRUUC8xLjEgMjAwIE9LDQpTZXJ2ZXI6IE1pY3Jvc29mdC1JSVMvNi4wDQpDb250ZW50LVR5cGU6IHRleHQvaHRtbA0KQ29udGVudC1MZW5ndGg6IDMyMDAwDQoNCjxodG1sPjxwcmU+KioqKioqKioqKjwvcHJlPjwvaHRtbD4="],"ip_gen_dist_list":[{"ip_start":"16.0.0.0","ip_end":"16.0.0.255","distribution":"seq","dir":"c","ip_offset":"1.0.0.0"},{"ip_start":"48.0.0.0","ip_end":"48.0.255.255","distribution":"seq","dir":"s","ip_offset":"1.0.0.0"}],"program_list":[{"commands":[{"name":"tx","buf_index":0},{"name":"rx","min_bytes":128}]},{"commands":[{"name":"rx","min_bytes":249},{"name":"tx","buf_index":1}]}],"templates":[{"client_template":{"program_index":0,"ip_gen":{"dist_client":{"index":0},"dist_server":{"index":1}},"cluster":{},"port":80,"cps":1.0},"server_template":{"program_index":1,"assoc":[{"port":80}]}}]}
```
when using "\astf\http_manual_commands.py" python file, the raw json data result is 
```
{'buf_list': ['R0VUIC8zMzg0IEhUVFAvMS4xDQpIb3N0OiAyMi4wLjAuMw0KQ29ubmVjdGlvbjogS2VlcC1BbGl2ZQ0KVXNlci1BZ2VudDogTW96aWxsYS80LjAgKGNvbXBhdGlibGU7IE1TSUUgNy4wOyBXaW5kb3dzIE5UIDUuMTsgU1YxOyAuTkVUIENMUiAxLjEuNDMyMjsgLk5FVCBDTFIgMi4wLjUwNzI3KQ0KQWNjZXB0OiAqLyoNCkFjY2VwdC1MYW5ndWFnZTogZW4tdXMNCkFjY2VwdC1FbmNvZGluZzogZ3ppcCwgZGVmbGF0ZSwgY29tcHJlc3MNCg0K', 'SFRUUC8xLjEgMjAwIE9LDQpTZXJ2ZXI6IE1pY3Jvc29mdC1JSVMvNi4wDQpDb250ZW50LVR5cGU6IHRleHQvaHRtbA0KQ29udGVudC1MZW5ndGg6IDMyMDAwDQoNCjxodG1sPjxwcmU+KioqKioqKioqKjwvcHJlPjwvaHRtbD4='], 'ip_gen_dist_list': [{'ip_start': '16.0.0.0', 'ip_end': '16.0.0.255', 'distribution': 'seq', 'dir': 'c', 'ip_offset': '1.0.0.0'}, {'ip_start': '48.0.0.0', 'ip_end': '48.0.255.255', 'distribution': 'seq', 'dir': 's', 'ip_offset': '1.0.0.0'}], 'program_list': [{'commands': [{'name': 'tx', 'buf_index': 0}, {'name': 'rx', 'min_bytes': 128}]}, {'commands': [{'name': 'rx', 'min_bytes': 249}, {'name': 'tx', 'buf_index': 1}]}], 'templates': [{'client_template': {'program_index': 0, 'ip_gen': {'dist_client': {'index': 0}, 'dist_server': {'index': 1}}, 'cluster': {}, 'port': 80, 'cps': 1}, 'server_template': {'program_index': 1, 'assoc': [{'port': 80}]}}]}
```
It's the same. one thing needs to be pointed out. some features in this pr are not implemented . for example pcap file support , i can't find third-party libraries to parse pcap file like dpkt in python. so i didn't do that.

**Comment by EgorBlagov** [comment]
> for example pcap file support , i can't find third-party libraries to parse pcap file like dpkt in python. so i didn't do that.

Hi, you could try to follow pcap4j, as we do in TRex STL GUI: https://github.com/cisco-system-traffic-generator/trex-stateless-gui/blob/master/src/main/java/com/exalttech/trex/ui/views/streams/viewer/PacketParser.java

**Comment by StanleyWu51** [comment]
Hi @EgorBlagov 
Thanks for your info, i will do that in the next few days.

**Comment by StanleyWu51** [comment]
Hi 
the feature pacp file parse has been done .it passed test cases from my side. please have a check if you have time. thanks

**Comment by EgorBlagov** [comment]
lgtm, Thanks

**Pull request merged**
