### PR TITLE
add astf client support

### PR DESCRIPTION
**Pull request by Emil-Gustafsson**
implementation proposal of astf client

### CODE REVIEW

**Comment by hhaim** [comment]
ASTF and STL share many common API - you should refactor the STL client and move the common RPC to a base object.

**Comment by Emil-Gustafsson** [comment]
i was also thinking about that, it is a bigger refactoring but a good idea.

**Comment by Emil-Gustafsson** [comment]
This needs to be tested, also there is probably more methods that is shared between them, just needs to find out if there is a difference in how to call them, the documentation is not always correct.

**Comment by EgorBlagov** [comment]
Hi, Emil

Thanks a lot for you PRs implemented, will check it in few days. Busy with other tasks.

Thanks & regards,
Egor.

**Pull request merged**
