### PR TITLE
Add task to upload archives to maven central

### PR DESCRIPTION
**Pull request by leomaatEric**
Now it can pack the jar, source, doc and pom then upload it to central maven stage repository via
./gradlew uploadArchives

### CODE REVIEW

**Comment by leomaatEric** [comment]
@Emil-Gustafsson ,
looks the Travis build will verify all tasks in gradle.build, but the new one "uploadArchives" requires the GPG keys and path which does not existed travis build environment, so it failed the build. 
Can it just ignore the "uploadArchieves" in travis build and how to achieve that?

**Comment by Emil-Gustafsson** [comment]
i think you need to add "script:" part in travis to not run all gradle tasks, the other is what is run before deploy

**Comment by leomaatEric** [comment]
@Emil-Gustafsson ,
Finally I got the approach to exclude specific task in gradle assemble/build, now Travis jobs are passed.

**Comment by leomaatEric** [comment]
> the keys needs to be uploded to travis so we dont expose them

What this change only does is packing the artifacts and deploy them to central maven stage repo, which is trigger manually. After that we need login to sonatype.com to release a formal version after check the content correction.

For now I just want to keep this non-fully automatic deployment on maven central, considering lots of version released each week, the automation can be done someday when the release is relative stale.

**Pull request merged**
