### PR TITLE
Set Link State method added

### PR DESCRIPTION
**Pull request by itsstilldre**
Change-Id: I8838878dff326d2c5c6f34eaa5c46c6bbda0f115

### CODE REVIEW

**Comment by itsstilldre** [comment]
Hi! This is my first pull request for t-rex java SDK. I am planning to create more, and hope for a good cooperation between us. If the code is not correct in some way, then please let me know and I will fix it.
Best Regards,
Gabor Selmeci

**Comment by Emil-Gustafsson** [comment]
would be nice to be able to set linkValue and attributes. You can set them to empty list if they have value null

**Comment by itsstilldre** [comment]
Ok. thanks for the feedback

**Comment by Emil-Gustafsson** [comment]
and if you dont know why you got build failed it is because the code is not formated with the google code formater. You can do that with the command "./gradlew goJF"

**Comment by itsstilldre** [comment]
> would be nice to be able to set linkValue and attributes. You can set them to empty list if they have value null

For Flow Control Mode and Promiscuous mode, there are already similar methods in TRexClient.java. I used these as reference to create this setLinkState method.

**Comment by Emil-Gustafsson** [comment]
okey, i now understand what you are after. i think it looks okey, can be merged after formatted

**Comment by itsstilldre** [comment]
Okay, thanks!

**Comment by Emil-Gustafsson** [comment]
thanks for fixing TRexAstfClient.java, the last commit added this fault. Are you ready so i can merge it now?

**Comment by itsstilldre** [comment]
Yes, I am ready, thank you!

**Pull request merged**
